version = 1

exclude_patterns = [
    "node_modules",
    "public"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "prettier"
enabled = true
